In [1]:
point = (35.6895,
    139.6917,)
point

(35.6895, 139.6917)

In [2]:
latitude =point[0]
longtitude =point[1]
print("latitude",latitude)
print("longtitude",longtitude)


latitude 35.6895
longtitude 139.6917


In [3]:
latitude,longtitude = point
print(latitude,longtitude)

35.6895 139.6917


## This section is for List

In [6]:
path = [
    (35.6895, 139.6917),
    (34.0522, -118.2437),
    (51.5074, -0.1278),
]  # List of tuples representing a path

print(path)
path.append((48.8566, 2.3522))
print("After appending:",path)

[(35.6895, 139.6917), (34.0522, -118.2437), (51.5074, -0.1278)]
After appending: [(35.6895, 139.6917), (34.0522, -118.2437), (51.5074, -0.1278), (48.8566, 2.3522)]


## Slicing List

In [14]:
start_two = path[:2]
print("First Two elements of list",start_two)
last_two = path[2:]
print("Last two elements of list",last_two)

## Average Latitude and longtitude

avg_lat = sum([x for x in path[0]]) / len(path)
avg_lon = sum([x for x in path[1]]) / len(path)
print (f"Average Latitude:",avg_lat)
print (f"Average Longtitude:",avg_lon)

First Two elements of list [(35.6895, 139.6917), (34.0522, -118.2437)]
Last two elements of list [(51.5074, -0.1278), (48.8566, 2.3522)]
Average Latitude: 43.8453
Average Longtitude: -21.047875


### Strings 

In [21]:
coordinate_string = "27.9881N, 86.9250E"
latitude,longtitude = coordinate_string.split(",")
print(latitude,longtitude)
lat = latitude[:-1]
lon = longtitude[:-1]
print(lat,lon)


27.9881N  86.9250E
27.9881  86.9250
 86.9250


In [29]:
address = "123 Everest Rd, Kathmandu, Nepal"
street,city,country = address.split(",")
print(f"Address: Street: {street}, City: {city}, Country:{country}")
newcity = "My city is San Francisco"
print(newcity)
oldcity=newcity.replace("San Francisco", "San Diago")
print(oldcity)

Address: Street: 123 Everest Rd, City:  Kathmandu, Country: Nepal
My city is San Francisco
My city is San Diago


### Loop over list

In [31]:
coordinates = [
    (35.6895, 139.6917),
    (34.0522, -118.2437),
    (51.5074, -0.1278),
]  # List of tuples representing coordinates
print(coordinates)
for lat,lon in coordinates:
    print(f"Latitute: {lat}, Longtitute : {lon}")

[(35.6895, 139.6917), (34.0522, -118.2437), (51.5074, -0.1278)]
Latitute: 35.6895, Longtitute : 139.6917
Latitute: 34.0522, Longtitute : -118.2437
Latitute: 51.5074, Longtitute : -0.1278


In [33]:
import numpy as np
# Reshape a 1D array into a 2D array
#arr_reshaped = np.arange(12)
arr_reshaped = np.arange(12).reshape((3, 4))
print(f"Reshaped 1D Array into 2D Array:\n{arr_reshaped}")

Reshaped 1D Array into 2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
sqrt = np.sqrt(arr_reshaped)
print(f"{sqrt}")

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]


In [38]:
square = np.square(sqrt)
print(f"{square}")

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [39]:
mean = np.mean(square)
std = np.std(square)
print(f"{mean}")
print(f"{std}")

5.5
3.452052529534664


In [40]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
first2rows = arr_2d[:2,:]
last2rows = arr_2d[1:,:2]
print(f"{first2rows}")
print(f"{last2rows}")

[[1 2 3]
 [4 5 6]]
[[4 5]
 [7 8]]


In [44]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterating through rows of the 2D array
print("Iterating over rows:")
for row in arr_2d:
    print(row)

# Iterating through each element of the 2D array
print("\nIterating over each element:")
for row in arr_2d:
    for element in row:
        print(element, end=" ")

Iterating over rows:
[1 2 3]
[4 5 6]
[7 8 9]

Iterating over each element:
1 2 3 4 5 6 7 8 9 

In [48]:
# Array of latitudes and longitudes
coords = np.array([[35.6895, 139.6917], [34.0522, -118.2437], [51.5074, -0.1278]])

print(f"Array of Coordinates\n{coords}")

# Convert degrees to radians
coords_radians = np.radians(coords)
print(f"Coordinates in radians:\n{coords_radians}")

Array of Coordinates
[[ 3.568950e+01  1.396917e+02]
 [ 3.405220e+01 -1.182437e+02]
 [ 5.150740e+01 -1.278000e-01]]
Coordinates in radians:
[[ 6.22899283e-01  2.43808010e+00]
 [ 5.94323008e-01 -2.06374188e+00]
 [ 8.98973719e-01 -2.23053078e-03]]


In [3]:
import numpy as np
# Array of latitudes and longitudes
coords = np.array([[35.6895, 139.6917], [34.0522, -118.2437], [51.5074, -0.1278]])

print(f"Array of Coordinates\n{coords}")

# Convert degrees to radians
coords_radians = np.radians(coords)
print(f"Coordinates in radians:\n{coords_radians}")

lat = coords_radians[:,0]
lon = coords_radians[:,1]

Array of Coordinates
[[ 3.568950e+01  1.396917e+02]
 [ 3.405220e+01 -1.182437e+02]
 [ 5.150740e+01 -1.278000e-01]]
Coordinates in radians:
[[ 6.22899283e-01  2.43808010e+00]
 [ 5.94323008e-01 -2.06374188e+00]
 [ 8.98973719e-01 -2.23053078e-03]]


array([0.62289928, 0.59432301, 0.89897372])